# Generated by Django 3.1.7 on 2021-03-21 18:17

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('sender', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1600, null=True)),
                ('selections', jsonfield.fields.JSONField(default=dict)),
                ('last_selection', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
